### ISSUE TITLE
Port existing site to OpenProducer platform

### ISSUE THREAD

**Issue by gusaus** [AMTVDigital/allmusictelevision#3]
We'll port existing site to OpenProducer platform when ready

**Comment by gusaus** [comment]
@justjazz I archived the site and pointed http://allmusictelevision.net/ to https://justjazz.tv/. We can revisit this issue if we decide to bring back a stand-alone site on the new WordPress platform.

**Comment by justjazz** [comment]
okay thanks!

Frederick Smith Jr
Founder/CEO
*All Music Television, LLC*
*Just Jazz TV*
310.365.1865 Cell
www.justjazz.tv Web

This electronic message, including any attachments, may contain
proprietary, confidential or privileged information for the sole use of the
intended recipient(s). You are hereby notified that any unauthorized
disclosure, copying, distribution, or use of this message is prohibited. If
you have received this message in error, please immediately notify the
sender by reply e-mail and delete it.
